### ISSUE TITLE
JEI Conflicts with Other Mods

### ISSUE THREAD

**Issue by Vyraal1** [codewarrior0/coop#1]
Custom recipes in Astral Sorcery's altar don't appear anymore in JEI after adding Coop. Can provide pack files if needed.

**Comment by codewarrior0** [comment]
Possibly related to the resource reload Coop does during the load complete phase to make sure it loads all registered chickens. If custom altar recipes vanish after pressing F3+T without Coop installed, the issue is with either Astral Sorcery or CraftTweaker.

**Comment by codewarrior0** [comment]
Not my fault.
