### ISSUE TITLE
Merge back into Roost?

### ISSUE THREAD

**Issue by timrwood** [codewarrior0/coop#5]
Hey @codewarrior0,

What do you think about merging back this work back into Roost? I don't have a ton of time to work on Roost these days, as I'm working full time and going to undergrad full time, but I could give you commit access and add you as a member on CurseForge.

I'm getting issues confusing coop and roost already at https://github.com/timrwood/roost/issues/60, so maybe we can unify to avoid more confusion?

**Comment by codewarrior0** [comment]
That would be fine with me. I only released the fork at the request of a friend (see timrwood/roost#54) and we'd both prefer if there were just one Roost.

**Comment by timrwood** [comment]
Cool, I added you as a collaborator on the GitHub repo, and wanted to confirm that this is you on CurseForge before adding you as a collaborator there also.

https://minecraft.curseforge.com/members/Rio

**Comment by codewarrior0** [comment]
Yep, that's me.
